/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se.cli;

public class AppCLI  {
    public static void main(String[] args) {
        AppController appController = new AppController();
        appController.run();
    }
  
}

